language: python

python: 3.7-dev

env:
  - TOXENV=py37

install: pip install -U tox-travis

script: tox -e ${TOXENV}


deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://upload.pypi.org/legacy/
    on:
      branch: master
    user: avidot
    password:
      secure: NPxOaz5D7Sb4Z3Xe8mxW2Ku/DwugCX3XxDrN4llyEoSYqODv+QxUUkZRFpuko46oNu1bmQI3r8mtkHmoVWGKkSMrNCaafgXpLPWL3VkIUAfWAFXE74dBC44IhdeYwMwBvfLfJoUNPm7pq71CIu+wEC98VE8a4dGPA6AmGuHmTEznygiYldhlGb5dgk06PAmwQmWPRXNOyzqQS03NFo3B/qEWzjiqUxPgQ5y7a5MpKaapihsRqY1CMAs4x8jenJPZmKkOphTEK+msdOVquxefk8vQ0M+oTUBr5Nclr6JW9RKYnNa9vEuKbOGbLtLyiYAoBuedDtsOaUxq/yMQXFjr3ySNLV6uLCnP+1Kf7QlzBdyA0mhFikX+inLH+cNPlwxi+I40t+Od1tswjEH8oE+fJpnFCKqre9Y4grH5MVpKK5IYqofBroCpZ+q/cOLFzxQMFvf5JBcfVtkXsRNkN1QQByW98/0goXAYwgroVBx/azfl6ALmCqBw06g3HqQk5wveg9FiLjqc7PZIWf8jQqsfRNFTNqjS+3DyMxRA0jjeaXAmgHL2405Cf1FatKJgm0RMd5BcVEABJrcQ6u2GvuIeTfcTcDVpZVleo9An1dWM8QhnZ4I5J1ZCAfEIR8ea4B0BwHr/eMt0RfLBOCldgdXL+znVeVZE/rmSKe/3TVKkI1A=
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://test.pypi.org/legacy/
    on:
      branch: develop
    user: avidot
    password:
      secure: NPxOaz5D7Sb4Z3Xe8mxW2Ku/DwugCX3XxDrN4llyEoSYqODv+QxUUkZRFpuko46oNu1bmQI3r8mtkHmoVWGKkSMrNCaafgXpLPWL3VkIUAfWAFXE74dBC44IhdeYwMwBvfLfJoUNPm7pq71CIu+wEC98VE8a4dGPA6AmGuHmTEznygiYldhlGb5dgk06PAmwQmWPRXNOyzqQS03NFo3B/qEWzjiqUxPgQ5y7a5MpKaapihsRqY1CMAs4x8jenJPZmKkOphTEK+msdOVquxefk8vQ0M+oTUBr5Nclr6JW9RKYnNa9vEuKbOGbLtLyiYAoBuedDtsOaUxq/yMQXFjr3ySNLV6uLCnP+1Kf7QlzBdyA0mhFikX+inLH+cNPlwxi+I40t+Od1tswjEH8oE+fJpnFCKqre9Y4grH5MVpKK5IYqofBroCpZ+q/cOLFzxQMFvf5JBcfVtkXsRNkN1QQByW98/0goXAYwgroVBx/azfl6ALmCqBw06g3HqQk5wveg9FiLjqc7PZIWf8jQqsfRNFTNqjS+3DyMxRA0jjeaXAmgHL2405Cf1FatKJgm0RMd5BcVEABJrcQ6u2GvuIeTfcTcDVpZVleo9An1dWM8QhnZ4I5J1ZCAfEIR8ea4B0BwHr/eMt0RfLBOCldgdXL+znVeVZE/rmSKe/3TVKkI1A=
