language: python

python: 3.7-dev

env:
  - TOXENV=py37

install: pip install -U tox-travis

script: tox -e ${TOXENV}


deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://upload.pypi.org/legacy/
    on:
      branch: master
    user: avidot
    password:
      secure: Vks5Mm9pQLCFm9QRzFKAdcLQ997X2sMEgKAFdaARWuXubx70nVzdt5G7gzauxyOGVu6YUb2RQvEmurM50S6BvNvq1217w/bqFK8/qR4D1ANTL5laL2nBDk5Afo25O/9P1crk4K7gBhJiJpEUQ+i/vdZ35oD00mDsHD49VrrmKvcOV8BckP+8JwvXjlWAfsEDFnNgwkR0FF2S2d6dL2gwFmW41xMmGRTthp5Tq7dFBgPD3A2iAg2Iu1WUqlXgIKI1vnBf+kDkGDJ5VC2fZgO+snmuvx1cs9vs5XrBy7opKgCB7iHmq41F9om6EBtQ8tGYAQ0XApO9mutOUdTFIy846TDEU1ieZX76P19hYa7Prg/GLeJQW3Y0+HusiqjiaJ9HGJXPsYc4RCLYJ6aIotcFFc7+UNFANXYKUZzoMCq/xrzxpobAK8wEIhvaz47GMRQbZQZiK/HLnBz4czUHZl0AUYSKDoYvSIRpOAJKVcnXtjsOTxAGnUz01/FKxenW5mH6IwMo9R0yNFUrq6GVaGFil8PKqbXljncPseqEDOT84aXo5YFy1gyZZdbciGrd+vLl/tq3aVY0OxIaBj7hATMd4mkxKIWodKu+TiP4+uH5MbKCz9+PaGzZvHB50CEcg9DdjyvE2G2KLTXcP0NUg/W3R0K0syTMu/46OTobktLwUT0=
  - provider: pypi
    distributions: sdist bdist_wheel
    server: https://test.pypi.org/legacy/
    on:
      branch: develop
    user: avidot
    password:
      secure: Vks5Mm9pQLCFm9QRzFKAdcLQ997X2sMEgKAFdaARWuXubx70nVzdt5G7gzauxyOGVu6YUb2RQvEmurM50S6BvNvq1217w/bqFK8/qR4D1ANTL5laL2nBDk5Afo25O/9P1crk4K7gBhJiJpEUQ+i/vdZ35oD00mDsHD49VrrmKvcOV8BckP+8JwvXjlWAfsEDFnNgwkR0FF2S2d6dL2gwFmW41xMmGRTthp5Tq7dFBgPD3A2iAg2Iu1WUqlXgIKI1vnBf+kDkGDJ5VC2fZgO+snmuvx1cs9vs5XrBy7opKgCB7iHmq41F9om6EBtQ8tGYAQ0XApO9mutOUdTFIy846TDEU1ieZX76P19hYa7Prg/GLeJQW3Y0+HusiqjiaJ9HGJXPsYc4RCLYJ6aIotcFFc7+UNFANXYKUZzoMCq/xrzxpobAK8wEIhvaz47GMRQbZQZiK/HLnBz4czUHZl0AUYSKDoYvSIRpOAJKVcnXtjsOTxAGnUz01/FKxenW5mH6IwMo9R0yNFUrq6GVaGFil8PKqbXljncPseqEDOT84aXo5YFy1gyZZdbciGrd+vLl/tq3aVY0OxIaBj7hATMd4mkxKIWodKu+TiP4+uH5MbKCz9+PaGzZvHB50CEcg9DdjyvE2G2KLTXcP0NUg/W3R0K0syTMu/46OTobktLwUT0=
