# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

dist: xenial
language: python
python: "3.7-dev"

env:
  - TOXENV=py37

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_dev.txt

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}

deploy:
- provider: pypi
  server: https://pypi.python.org/pypi
  on:
    branch: master
  user: avidot
  password:
    secure: "YRwPDcoFyL0ZXGnskT2eoEnKocYfLppmDZNG7OlOhN7kJsrVSEzKYmykjwL+zF5DapG3RhZ1A32Jd5bwizWVGw+Xeyo28n4darts7oy946Bqx/slkiW03SOm5C3WO2b6fyI3tMfl4//qnN6Jr5zFU0bpDhg3GOIMnl/TcrLffSPADwDm9UTkVUsOUKBYggjFw9Cv+xroofOIKoZpnUyjfBUWb9IgR+O6TeW8QBhK/iUilvkgsVby3iKB0NM7ZnrZsQT5zrIkdYRxR0L0MaOJfQiPsSqtNFnWiK+hebBSIxtw7B2wFrc4DCUY8FPhX74be5ZEL5bUms21imJ0cvSMEFoxWjFwQAt0ks963vpvWAhmBdDE/JKVretTmMvU8jXjD3ASIeIWvBPPS76ph2EaOFtirGnLYHIEkfNvoQRI8dhQJ20FCdZd37V2c/8hxB3KpMFFXsv7HpVw6r09X1/CL3zVuauii9E8O9mwIZdE+zR0rR/liqSVP8pXrTybozOFUhErQ4z7LHRcisYzj1giWt5R3a1KQcT+c4BFaxMUMTdy1NTcK4YK+jrxmOuBg9439BtIQuCPZRW6C8afzTPWZ1P0DYXFYgaKR1C/xjbzqICyvq1/GWi/LDoF2JxV/nERv9YKKAAs4n7+7F3SpZwvEODPqvtvz2p+bA0YI2W5SG8="
- provider: pypi
  server: https://testpypi.python.org/pypi
  on:
    branch: develop
  user: avidot
  password:
    secure: "YRwPDcoFyL0ZXGnskT2eoEnKocYfLppmDZNG7OlOhN7kJsrVSEzKYmykjwL+zF5DapG3RhZ1A32Jd5bwizWVGw+Xeyo28n4darts7oy946Bqx/slkiW03SOm5C3WO2b6fyI3tMfl4//qnN6Jr5zFU0bpDhg3GOIMnl/TcrLffSPADwDm9UTkVUsOUKBYggjFw9Cv+xroofOIKoZpnUyjfBUWb9IgR+O6TeW8QBhK/iUilvkgsVby3iKB0NM7ZnrZsQT5zrIkdYRxR0L0MaOJfQiPsSqtNFnWiK+hebBSIxtw7B2wFrc4DCUY8FPhX74be5ZEL5bUms21imJ0cvSMEFoxWjFwQAt0ks963vpvWAhmBdDE/JKVretTmMvU8jXjD3ASIeIWvBPPS76ph2EaOFtirGnLYHIEkfNvoQRI8dhQJ20FCdZd37V2c/8hxB3KpMFFXsv7HpVw6r09X1/CL3zVuauii9E8O9mwIZdE+zR0rR/liqSVP8pXrTybozOFUhErQ4z7LHRcisYzj1giWt5R3a1KQcT+c4BFaxMUMTdy1NTcK4YK+jrxmOuBg9439BtIQuCPZRW6C8afzTPWZ1P0DYXFYgaKR1C/xjbzqICyvq1/GWi/LDoF2JxV/nERv9YKKAAs4n7+7F3SpZwvEODPqvtvz2p+bA0YI2W5SG8="
